version: "3.3"
services:
  squid:
    ports:
      - 3128:3128
    image: b4tman/squid:latest
    volumes:
      - './config:/etc/squid/conf.d:ro'
    container_name: dockersquid_rotate
    environment:
      - 'SQUID_CONFIG_FILE=/etc/squid/conf.d/squid.conf'
  hola1:
    ports:
      - 9021:8080
    image: yarmak/hola-proxy:latest
    command: "-country us -proxy-type peer -proxy http://127.0.0.1:9024"
    container_name: dockerhola_1
  hola2:
    ports:
      - 9022:8080
    image: yarmak/hola-proxy:latest
    command: "-country ch -proxy-type peer -proxy http://127.0.0.1:9025"
    container_name: dockerhola_2
  hola3:
    ports:
      - 9023:8080
    image: yarmak/hola-proxy:latest
    command: "-country it -proxy-type peer -proxy http://127.0.0.1:9024"
    container_name: dockerhola_3
  windscribe1:
    ports:
      - 9024:28080
    image: yarmak/windscribe-proxy:latest
    command: "-location France/Paris"
    container_name: windscribe_1
  operaproxy1:
    ports:
      - 9025:18080
    image: yarmak/opera-proxy:latest
    command: "-country EU"
    container_name: operaproxy1
  vpn12:
    ports:
      - "49153:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_12
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/nl-free-01.protonvpn.com.udp.ovpn:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
  vpn13:
    ports:
      - "49154:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_13
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/nl-free-02.protonvpn.com.udp.ovpn:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
  vpn14:
    ports:
      - "49155:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_14
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/us-free-01.protonvpn.com.udp.ovpn:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
