version: "3.3"
services:
  squid:
    ports:
      - 3128:3128
    image: b4tman/squid:latest
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf
      - ./config/allowed_ip.txt:/etc/squid/allowed_ip.txt
    container_name: dockersquid_rotate
  hola1:
    ports:
      - 9021:8080
    image: yarmak/hola-proxy:latest
    command: "-country us -proxy-type peer -proxy http://127.0.0.1:49152"
    container_name: dockerhola_1
  hola2:
    ports:
      - 9022:8080
    image: yarmak/hola-proxy:latest
    command: "-country ch -proxy-type peer -proxy http://127.0.0.1:49153"
    container_name: dockerhola_2
  hola3:
    ports:
      - 9023:8080
    image: yarmak/hola-proxy:latest
    command: "-country it -proxy-type peer -proxy http://127.0.0.1:49154"
    container_name: dockerhola_3
  windscribe1:
    ports:
      - 9024:28080
    image: yarmak/windscribe-proxy:latest
    command: "-location Germany/Frankfurt -proxy http://127.0.0.1:49152"
    container_name: windscribe_1
  windscribe2:
    ports:
      - 9025:28080
    image: yarmak/windscribe-proxy:latest
    command: "-location Germany/Frankfurt -proxy http://127.0.0.1:49153"
    container_name: windscribe_2
  windscribe3:
    ports:
      - 9026:28080
    image: yarmak/windscribe-proxy:latest
    command: "-location Germany/Frankfurt -proxy http://127.0.0.1:49154"
    container_name: windscribe_3
  operaproxy1:
    ports:
      - 9027:18080
    image: yarmak/opera-proxy:latest
    command: "-country EU -proxy http://127.0.0.1:49154"
    container_name: operaproxy1
  operaproxy2:
    ports:
      - 9028:18080
    image: yarmak/opera-proxy:latest
    command: "-country EU -proxy http://127.0.0.1:49155"
    container_name: operaproxy2
  operaproxy3:
    ports:
      - 9029:18080
    image: yarmak/opera-proxy:latest
    command: "-country EU -proxy http://127.0.0.1:49155"
    container_name: operaproxy3
  vpn11:
    ports:
      - "49152:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_11
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/available:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
  vpn12:
    ports:
      - "49153:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_12
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/nl-free-01.protonvpn.com.udp.ovpn:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
  vpn13:
    ports:
      - "49154:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_13
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/nl-free-02.protonvpn.com.udp.ovpn:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
  vpn14:
    ports:
      - "49155:3128"
    image: curve25519xsalsa20poly1305/openvpn
    container_name: dockervpn_14
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - "./openvpn/us-free-01.protonvpn.com.udp.ovpn:/vpn:ro"
    environment:
      - OPENVPN_CONFIG=/vpn/vpn.ovpn
